### ISSUE TITLE
BUG: Trying to create a container that already exists throws 409

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#177]

**Comment by pirog** [comment]
```
Error: HTTP code is 409 which indicates error: undefined - Conflict, The name kalabox_skydns is already assigned to 882dd5788d3c. You have to delete (or rename) that container to be able to assign kalabox_skydns to a container again.

    at Modem.buildPayload (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:198:15)
    at IncomingMessage.<anonymous> (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:174:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:883:14
    at process._tickCallback (node.js:415:13)
```

**Comment by bcauldwell** [comment]
FIXED: it will now return a well formed error message.
