### ISSUE TITLE
BUG: App will try to load plugins before they exist

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#258]

**Comment by pirog** [comment]
If you are running `kbox install` on an app for the first time and that app has external plugins ... then the `npm install` part of `kbox install` needs to happen before kbox attempts to load the plugins. 

to replicate just update to the latest kbox and app examples. go into `pressflow7` and delete your `node_modules` folder and then run `kbox install`. it should throw something like this:

```
Possibly unhandled Error: Plugin "kalabox-plugin-pressflow7-env" could not be loaded.
    at loadRawPlugin (/Users/mpirog/Desktop/kalabox/lib/core/plugin.js:43:11)
    at Object.exports.load (/Users/mpirog/Desktop/kalabox/lib/core/plugin.js:98:19)
    at /Users/mpirog/Desktop/kalabox/lib/app.js:122:32
    at Array.forEach (native)
    at /Users/mpirog/Desktop/kalabox/lib/app.js:121:17
    at Object.exports.override (/Users/mpirog/Desktop/kalabox/lib/core/deps.js:153:3)
    at Object.exports.loadPlugins (/Users/mpirog/Desktop/kalabox/lib/app.js:120:13)
    at initWithApp (/Users/mpirog/Desktop/kalabox/bin/kbox.js:68:12)
    at /Users/mpirog/Desktop/kalabox/bin/kbox.js:206:7
    at /Users/mpirog/Desktop/kalabox/lib/app.js:198:11
    at /Users/mpirog/Desktop/kalabox/node_modules/async/lib/async.js:254:17
    at done (/Users/mpirog/Desktop/kalabox/node_modules/async/lib/async.js:135:19)
    at /Users/mpirog/Desktop/kalabox/node_modules/async/lib/async.js:32:16
    at /Users/mpirog/Desktop/kalabox/node_modules/async/lib/async.js:251:21
    at /Users/mpirog/Desktop/kalabox/lib/app.js:190:13
    at Object.exports.getAppDir (/Users/mpirog/Desktop/kalabox/lib/app/discovery.js:179:5)
```
