### ISSUE TITLE
Too many listeners?

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#305]

**Comment by pirog** [comment]
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:160:15)
    at ReadStream.Stream.pipe (stream.js:118:10)
    at handler (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/lib/docker.js:429:21)
    at /Users/mpirog/Desktop/kalabox/node_modules/dockerode/lib/container.js:418:5
    at Modem.buildPayload (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:214:7)
    at ClientRequest.<anonymous> (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:163:12)
    at ClientRequest.EventEmitter.emit (events.js:117:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1625:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:119:23)
    at Socket.socketOnData [as ondata] (http.js:1520:20)
    at TCP.onread (net.js:510:27)
```

**Comment by pirog** [comment]
To replicate

1. Checkout https://github.com/kalabox/kalabox/tree/304-engineRun
2. Use the drupal7 app example
3. Use https://github.com/kalabox/kalabox-plugin-drush/tree/304-engine-run for the drush plugin
4. install and try to start

**Comment by pirog** [comment]
@bcauldwell it seems like 304 resolved this so going to move to done
