### ISSUE TITLE
Strange Access error on syncthing / container

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#329]
```
john@kalamuna:~/kalabox/apps/k2a$ kbox start
info: DOCKER => Starting container. 1b968b341c323e2c4fa5baa08a00f9b42ef8da51ba1ade9d1302594869bf10ea
info: DOCKER => Container started. 1b968b341c323e2c4fa5baa08a00f9b42ef8da51ba1ade9d1302594869bf10ea
info: DOCKER => Starting container. 7cd585cd51fee622b7ab6816e36fa4d52ad240d1a2cfde85c88f6d3155bcd3b0
info: DOCKER => Container already started. 7cd585cd51fee622b7ab6816e36fa4d52ad240d1a2cfde85c88f6d3155bcd3b0
info: DOCKER => Starting container. 4b17e86f1c1da8f8eaea7b494415a1d12500278aed4ad0db4c308034017c9c0a
info: DOCKER => Container already started. 4b17e86f1c1da8f8eaea7b494415a1d12500278aed4ad0db4c308034017c9c0a
info: DOCKER => Starting container. 9b9edfd8ad30973c0468c245e8848632541fdb1603c97b15d8abacb0a3feb086
info: DOCKER => Container already started. 9b9edfd8ad30973c0468c245e8848632541fdb1603c97b15d8abacb0a3feb086
info: DOCKER => Stopping container. kalabox_syncthing
info: DOCKER => Container stopped. kalabox_syncthing
info: DOCKER => Removing container. kalabox_syncthing
info: DOCKER => Container removed. kalabox_syncthing
info: DOCKER => Creating container.
info: DOCKER => Container created. cid=14f056520aa1617a40520c3576a772b128105e60042f1f258e269a2940fbafe8, name=kalabox_syncthing
info: DOCKER => Starting container. kalabox_syncthing
info: DOCKER => Container started. kalabox_syncthing
 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by labboy0276** [comment]
Also

http://127.0.0.1:60008/ does not work due to this, http://10.13.37.42:60008/ works, but it isnt seeing the folder / app.

**Comment by labboy0276** [comment]
```
john@kalamuna:~/kalastack$ ls -al ~/.kalabox/bin
total 10616
drwxrwxr-x 2 john john     4096 Mar 13 12:56 .
drwxrwxr-x 8 john john     4096 Mar 13 13:01 ..
-rw-rw-r-- 1 john john 10860536 Mar 13 12:56 syncthing
```
Shows that there is no executable access, running chmod +x syncthing fixed this

**Comment by pirog** [comment]
sycnthing needs to be executable. This should happen in the install. I added an additional check for this for now. 

When we finally switch things over to our new installer framework we will clean it up a bit.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/tree/linux-fixes
