### ISSUE TITLE
Ran out of space 

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#372]
I only have 3 sites installed (2 have large file dirs 5gb+) and now i am getting this when I am trying to do a 4th:

```
john@kalamuna:~/kalabox/apps/kfp/code$ kbox rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' deep-clean.14c5ded5-f4cb-41a0-8225-6643228e55d4@appserver.deep-clean.14c5ded5-f4cb-41a0-8225-6643228e55d4.drush.in:files/ sites/default/files/
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
Warning: Permanently added '[appserver.deep-clean.14c5ded5-f4cb-41a0-8225-6643228e55d4.drush.in]:2222,[23.253.170.101]:2222' (RSA) to the list of known hosts.
receiving incremental file list
kettering/Franklin Academy 990.pdf
     9491282  59%    4.04MB/s    0:00:01  
rsync: write failed on "/data/sites/default/files/kettering/Franklin Academy 990.pdf": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(322) [receiver=3.0.9]
rsync: connection unexpectedly closed (27454 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [generator=3.0.9]
info: DOCKER => RUN container shutting down.
```

And this error when I try to stop:

```
john@kalamuna:~/kalabox/apps/kfp/code$ kbox stop
info: SERVICES => Startup services need to be started.
info: DOCKER => Stopping container. cccca97a344b43724ca6298aa1362b0fd456b6af67191599c25c0d13e2ff4236
info: DOCKER => Container stopped. cccca97a344b43724ca6298aa1362b0fd456b6af67191599c25c0d13e2ff4236
info: DOCKER => Stopping container. e4949d070a219a39ff32661d84dc1ac4306fc96315452eed99516ba70e48248e
info: DOCKER => Container stopped. e4949d070a219a39ff32661d84dc1ac4306fc96315452eed99516ba70e48248e
info: DOCKER => Stopping container. c7d760bb3d3c884d5393af33eb8df65e87fff0d1462e0b29a3a98419b50fcd39
info: DOCKER => Container already stopped. c7d760bb3d3c884d5393af33eb8df65e87fff0d1462e0b29a3a98419b50fcd39
info: DOCKER => Stopping container. c18db2baada0344bcd3870404a05a6dd32c8b70a36b8701d190688c1c10b9ac9
info: DOCKER => Container already stopped. c18db2baada0344bcd3870404a05a6dd32c8b70a36b8701d190688c1c10b9ac9
info: DOCKER => Starting container. cccca97a344b43724ca6298aa1362b0fd456b6af67191599c25c0d13e2ff4236
info: DOCKER => Error while starting container. Error: HTTP code is 500 which indicates error: server error - Cannot start container cccca97a344b43724ca6298aa1362b0fd456b6af67191599c25c0d13e2ff4236: write /mnt/sda1/var/lib/docker/execdriver/native/cccca97a344b43724ca6298aa1362b0fd456b6af67191599c25c0d13e2ff4236/state.json: no space left on device

    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
info: DOCKER => Starting container. e4949d070a219a39ff32661d84dc1ac4306fc96315452eed99516ba70e48248e
info: DOCKER => Error while starting container. Error: HTTP code is 500 which indicates error: server error - Cannot start container e4949d070a219a39ff32661d84dc1ac4306fc96315452eed99516ba70e48248e: write /mnt/sda1/var/lib/docker/execdriver/native/e4949d070a219a39ff32661d84dc1ac4306fc96315452eed99516ba70e48248e/container.json: no space left on device

    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
info: DOCKER => Starting container. c7d760bb3d3c884d5393af33eb8df65e87fff0d1462e0b29a3a98419b50fcd39
info: DOCKER => Error while starting container. Error: HTTP code is 500 which indicates error: server error - Cannot start container c7d760bb3d3c884d5393af33eb8df65e87fff0d1462e0b29a3a98419b50fcd39: write /mnt/sda1/var/lib/docker/execdriver/native/c7d760bb3d3c884d5393af33eb8df65e87fff0d1462e0b29a3a98419b50fcd39/container.json: no space left on device

    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
info: DOCKER => Starting container. c18db2baada0344bcd3870404a05a6dd32c8b70a36b8701d190688c1c10b9ac9
info: DOCKER => Error while starting container. Error: HTTP code is 500 which indicates error: server error - Cannot start container c18db2baada0344bcd3870404a05a6dd32c8b70a36b8701d190688c1c10b9ac9: write /mnt/sda1/var/lib/docker/execdriver/native/c18db2baada0344bcd3870404a05a6dd32c8b70a36b8701d190688c1c10b9ac9/container.json: no space left on device

    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
info: DOCKER => Stopping container. 80a4ef7d872cbb1cbce579609b4bdca993c041732699441e0ba76662da14945e
info: DOCKER => Container already stopped. 80a4ef7d872cbb1cbce579609b4bdca993c041732699441e0ba76662da14945e
info: DOCKER => Stopping container. 0ddb2573583e24a81448037e8af44c2a78f8492dd4a1afc307f394cf3d1d9613
info: DOCKER => Container already stopped. 0ddb2573583e24a81448037e8af44c2a78f8492dd4a1afc307f394cf3d1d9613
info: DOCKER => Stopping container. 0f2cff77d299173a22315a28d43aa998eed0038b636d8281e6c02184095e2726
info: DOCKER => Container already stopped. 0f2cff77d299173a22315a28d43aa998eed0038b636d8281e6c02184095e2726
info: DOCKER => Creating container.
info: DOCKER => Error creating container. Error: HTTP code is 500 which indicates error: server error - Insertion failed because database is full: database or disk is full

    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
info: SHARE => Error while restarting. Error: HTTP code is 500 which indicates error: server error - Insertion failed because database is full: database or disk is full

    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
error: While running task [stop] Error: EVENTS => Error while dispatching event listeners. Error: While running task [stop] Error: EVENTS => Error while dispatching event listeners.
    at Task._wrapError (/home/john/kb2/lib/core/task.js:76:10)
    at /home/john/kb2/lib/core/task.js:148:20
    at /home/john/kb2/lib/app.js:477:21
    at doneProxy (/home/john/kb2/lib/core/events.js:122:7)
    at /home/john/kb2/lib/core/events.js:141:7
    at /home/john/kb2/node_modules/async/lib/async.js:151:21
    at /home/john/kb2/lib/share.js:292:5
    at tryCatcher (/home/john/kb2/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/john/kb2/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/john/kb2/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/john/kb2/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/john/kb2/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/home/john/kb2/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/home/john/kb2/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:448:13)

/home/john/kb2/bin/kbox.js:124
    throw err;
          ^
Error: While running task [stop] Error: EVENTS => Error while dispatching event listeners.
    at Task._wrapError (/home/john/kb2/lib/core/task.js:76:10)
    at /home/john/kb2/lib/core/task.js:148:20
    at /home/john/kb2/lib/app.js:477:21
    at doneProxy (/home/john/kb2/lib/core/events.js:122:7)
    at /home/john/kb2/lib/core/events.js:141:7
    at /home/john/kb2/node_modules/async/lib/async.js:151:21
    at /home/john/kb2/lib/share.js:292:5
    at tryCatcher (/home/john/kb2/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/john/kb2/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/john/kb2/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/john/kb2/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/john/kb2/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/home/john/kb2/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/home/john/kb2/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:448:13)
john@kalamuna:~/kalabox/apps/kfp/code$ 
```

**Comment by pirog** [comment]
Go into virtual box and tell give us some data about the "storage" of the KB2 machine.

**Comment by labboy0276** [comment]
I dont think du -h or df -h is the right CLI commands to get this

What should I use?

**Comment by pirog** [comment]
did you read the comment above yours?

**Comment by labboy0276** [comment]
ok storage tab of VM, I was think literally go into the VM..

Anyway, virtual size 19.53 GB, actual size 17.95 GB

Granted I just removed 1.5 GBs of data after posting this issue as well

**Comment by pirog** [comment]
Add more stuff if you can to see if you can replicate your error and then check the space again.

**Comment by labboy0276** [comment]
I went into my b2d, like this:
boot2docker --vm="Kalabox2" ssh
```
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.5G    205.9M      3.3G   6% /
tmpfs                     3.5G    205.9M      3.3G   6% /
tmpfs                     1.9G         0      1.9G   0% /dev/shm
/dev/sda1                18.2G     16.1G      1.2G  93% /mnt/sda1
cgroup                    1.9G         0      1.9G   0% /sys/fs/cgroup
none                    591.3G    178.9G    412.4G  30% /Users
/dev/sda1                18.2G     16.1G      1.2G  93% /mnt/sda1/var/lib/docker/aufs
```

it appears my /dev/sda1 is the VM as I started to dload more files via rsync and it is increasing in size.

**Comment by pirog** [comment]
increasing in size or used?

**Comment by labboy0276** [comment]
yes increasing in used size, i stand corrected, I continued on the rsync again and here it is again when i ssh back in:

```
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.5G    205.9M      3.3G   6% /
tmpfs                     3.5G    205.9M      3.3G   6% /
tmpfs                     1.9G         0      1.9G   0% /dev/shm
/dev/sda1                18.2G     16.6G    658.1M  96% /mnt/sda1
cgroup                    1.9G         0      1.9G   0% /sys/fs/cgroup
none                    591.3G    178.9G    412.4G  30% /Users
/dev/sda1                18.2G     16.6G    658.1M  96% /mnt/sda1/var/lib/docker/aufs
```

**Comment by pirog** [comment]
K. lets wait for it to fill up.

The way this disk is set up on the VM is that it should actually dynamically increase the disk size as it gets filled so it will be interesting to see why that presumably does not happen.

**Comment by labboy0276** [comment]
OK i will continue on the rsync and report back

**Comment by labboy0276** [comment]
and now it is full again:

```
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.5G    205.9M      3.3G   6% /
tmpfs                     3.5G    205.9M      3.3G   6% /
tmpfs                     1.9G    216.0K      1.9G   0% /dev/shm
/dev/sda1                18.2G     18.1G         0 100% /mnt/sda1
cgroup                    1.9G         0      1.9G   0% /sys/fs/cgroup
none                    591.3G    179.0G    412.3G  30% /Users
/dev/sda1                18.2G     18.1G         0 100% /mnt/sda1/var/lib/docker/aufs
none                     18.2G     18.1G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/cccca97a344b43724ca6298aa1362b0fd456b6af67191599c25c0d13e2ff4236
none                     18.2G     18.1G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/e4949d070a219a39ff32661d84dc1ac4306fc96315452eed99516ba70e48248e
none                     18.2G     18.1G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/c7d760bb3d3c884d5393af33eb8df65e87fff0d1462e0b29a3a98419b50fcd39
none                     18.2G     18.1G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/c18db2baada0344bcd3870404a05a6dd32c8b70a36b8701d190688c1c10b9ac9
```

**Comment by labboy0276** [comment]
OK

Did a kbox down, then kbox up.  Tried to rsync more files into another app:

```
john@kalamuna:~/kalabox/apps/fiksu$ kbox rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb@appserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in:files/ sites/default/files/
info: DOCKER => Creating RUN container.
error: While running task [rsync] Error: HTTP code is 500 which indicates error: server error - Insertion failed because database is full: database or disk is full
 Error: While running task [rsync] Error: HTTP code is 500 which indicates error: server error - Insertion failed because database is full: database or disk is full

    at Task._wrapError (/home/john/kb2/lib/core/task.js:76:10)
    at /home/john/kb2/lib/core/task.js:148:20
    at /home/john/kb2/node_modules/kalabox-engine-docker/docker.js:481:9
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/lib/docker.js:33:20
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:210:7
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

/home/john/kb2/bin/kbox.js:124
    throw err;
          ^
Error: While running task [rsync] Error: HTTP code is 500 which indicates error: server error - Insertion failed because database is full: database or disk is full

    at Task._wrapError (/home/john/kb2/lib/core/task.js:76:10)
    at /home/john/kb2/lib/core/task.js:148:20
    at /home/john/kb2/node_modules/kalabox-engine-docker/docker.js:481:9
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/lib/docker.js:33:20
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:210:7
    at getCause (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

```

And the VM size:
```
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.5G    205.8M      3.3G   6% /
tmpfs                     3.5G    205.8M      3.3G   6% /
tmpfs                     1.9G         0      1.9G   0% /dev/shm
/dev/sda1                18.2G     18.2G         0 100% /mnt/sda1
cgroup                    1.9G         0      1.9G   0% /sys/fs/cgroup
none                    591.3G    179.0G    412.3G  30% /Users
/dev/sda1                18.2G     18.2G         0 100% /mnt/sda1/var/lib/docker/aufs
```

**Comment by labboy0276** [comment]
Here is a <b>workaround</b> that may only work for linux:

1. go into ~/.kalabox/.provider
2. and edit profile
3. you can change # VM disk image size in MB (DiskSize = 20000)

destroy the VM (not uninstall kb2) and reprovision

**Comment by labboy0276** [comment]
Also

I noticed today, when I did this for 0.6.0, not that the version matters, but I had to remove the namservers from /etc/resolvconf/resolv.conf.d/head && resolvconf -u

Otherwise it was taking over hours for kb2 to install

**Comment by pirog** [comment]
Did you use the uninstall script?

On Wednesday, April 15, 2015, John Ouellet <notifications@github.com> wrote:

> Also
>
> I noticed today, when I did this for 0.6.0, not that the version matters,
> but I had to remove the namservers from /etc/resolvconf/resolv.conf.d/head
> && resolvconf -u
>
> Otherwise it was taking over hours for kb2 to install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/372#issuecomment-93482477>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
No, you told me not to when editing the profile to increase the size.  

Everything is fine now, I just threw that tidbit on the workaround.

**Comment by pirog** [comment]
K. Well that is why it didn't remove the DNS.

Did everything else in the install go ok?

Where is the workaround for increasing the VM size. Might be a good article
to add to the wiki for now.

On Wednesday, April 15, 2015, John Ouellet <notifications@github.com> wrote:

> No, you told me not to when editing the profile to increase the size.
>
> Everything is fine now, I just threw that tidbit on the workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/372#issuecomment-93485806>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
It is on this issue, 4 comments up

**Comment by labboy0276** [comment]
and yes everything else went fabulously

**Comment by pirog** [comment]
Can you move it to the kalabox wiki? Let ,e know if you need perms to add a
page

On Wednesday, April 15, 2015, John Ouellet <notifications@github.com> wrote:

> and yes everything else went fabulously
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/372#issuecomment-93486990>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
otay

**Comment by labboy0276** [comment]
done

**Comment by pirog** [comment]
edited it a bit. will try to work on a "disksize" flag for ` kbox provision` today
