### ISSUE TITLE
When Linux Headers Update, Vagrant / Kalabox says no

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#383]
This is an age old problem I had with KB1 as well.   However now the message isn't as clear.  When you update your Linux Headers, Vagrant needs a command to update its kernel.  It is lame, but this is what happens now on KB2:

```
john@kalamuna:~/kalabox/apps$ kbox up
info: B2D => Starting up...
info: B2D => Error while starting up. Error: B2D => Error running command.
    at /home/john/kb2/lib/util/shell.js:49:13
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
error: While running task [up] Error: B2D => Error while starting up. Error: While running task [up] Error: B2D => Error while starting up.
    at Task._wrapError (/home/john/kb2/lib/core/task.js:76:10)
    at /home/john/kb2/lib/core/task.js:148:20
    at callback (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:129:7)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:107:11
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:38:9
    at /home/john/kb2/lib/util/shell.js:53:5
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

/home/john/kb2/bin/kbox.js:124
    throw err;
          ^
Error: While running task [up] Error: B2D => Error while starting up.
    at Task._wrapError (/home/john/kb2/lib/core/task.js:76:10)
    at /home/john/kb2/lib/core/task.js:148:20
    at callback (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:129:7)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:107:11
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:38:9
    at /home/john/kb2/lib/util/shell.js:53:5
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

On old KB1 you would get a message like this:
```
john@kalamuna:~/kalastack$ vagrant up
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
```

After running said command above you get:
```
john@kalamuna:~/kalastack$ VBoxManage --version
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (3.13.0-49-generic) or it failed to
         load. Please recompile the kernel module and install it by

           sudo /etc/init.d/vboxdrv setup

         You will not be able to start VMs until this problem is fixed.
4.3.16r95972
```

And then:
```
john@kalamuna:~/kalabox/apps$ sudo /etc/init.d/vboxdrv setup
[sudo] password for john: 
Stopping VirtualBox kernel modules ...done.
Recompiling VirtualBox kernel modules ...done.
Starting VirtualBox kernel modules ...done.
john@kalamuna:~/kalabox/apps$ kbox up
info: B2D => Starting up...
Kalabox engine has been activated.
info: B2D => Started up.
```

Q'PLAH!!!

Maybe a more descriptive message?

**Comment by bcauldwell** [comment]
The error message not showing up is due to a bug that I fixed for version 0.6.0. In the mean time it should have been logged correctly in ~/.kalabox/logs/

**Comment by pirog** [comment]
@ labboy0276 next kernel update can you test this and confirm it reports the error correctly?

**Comment by labboy0276** [comment]
Alrighty

**Comment by labboy0276** [comment]
@pirog @bcauldwell Still no bueno after a header update:

```
john@kalamuna:~/kalabox/apps$ kbox up
info: B2D => Starting up...
info: B2D => Error while starting up. code: 1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

code: 1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

john@kalamuna:~/kalabox/apps$ kbox up
info: B2D => Starting up...
info: B2D => Error while starting up. code: 1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

code: 1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

john@kalamuna:~/kalabox/apps$ kbox down
info: B2D => Shutting down.
Kalabox engine has been deactivated.
info: B2D => Shut down.
john@kalamuna:~/kalabox/apps$ kbox up
info: B2D => Starting up...
info: B2D => Error while starting up. code: 1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

code: 1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

john@kalamuna:~/kalabox/apps$ 
```

I then ran:

```
john@kalamuna:~/kalabox/apps$ sudo /etc/init.d/vboxdrv setup
[sudo] password for john: 
Stopping VirtualBox kernel modules ...done.
Recompiling VirtualBox kernel modules ...done.
Starting VirtualBox kernel modules ...done.
john@kalamuna:~/kalabox/apps$ kbox up
info: B2D => Starting up...
Kalabox engine has been activated.
info: B2D => Started up.
john@kalamuna:~/kalabox/apps$ 
```

**Comment by labboy0276** [comment]
I guess all we would need to do is this case is to have it say to run the command:

```
sudo /etc/init.d/vboxdrv setup
```
When it fails for this particular command of kbox up on linux
